services:
  api-migrate:
    image: ghcr.io/${GHCR_REPOSITORY:?GHCR_REPOSITORY is required}/api-release:${IMAGE_TAG:?IMAGE_TAG is required}
  api:
    image: ghcr.io/${GHCR_REPOSITORY}/api:${IMAGE_TAG}
  web:
    image: ghcr.io/${GHCR_REPOSITORY}/web:${IMAGE_TAG}
