import { ArrowRight, BellRing, CalendarCheck, CalendarClock, ListRestart, MessageSquareText, Send, UserRoundCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { trackEvent } from '../analytics';
import { MarketingLayout } from './MarketingLayout';

export function TelegramBookingPage() {
  return <MarketingLayout>
    <section className="marketing-hero"><nav className="breadcrumbs" aria-label="Хлебные крошки"><Link to="/">Главная</Link><span aria-hidden="true">/</span><span>Запись через Telegram</span></nav><p className="eyebrow">Telegram-бот для записи</p><h1>Онлайн-запись клиентов через Телеграм</h1><p>Клиент выбирает услугу, специалиста и свободное время в вашем Telegram-боте. Slotty учитывает длительность визита и синхронизирует запись с рабочим расписанием.</p><div className="landing-actions"><Link className="primary-button lime-button" to="/app?mode=register" onClick={() => { trackEvent('landing_start_trial', { source: 'telegram_booking' }); trackEvent('registration_start', { source: 'telegram_booking' }); }}>Подключить Slotty <ArrowRight size={17} /></Link><Link className="text-button" to="/online-zapis">Возможности онлайн-записи</Link></div></section>
    <section className="telegram-process" aria-labelledby="telegram-process-title"><div><Send size={30} aria-hidden="true" /><p className="eyebrow">Без переписки</p><h2 id="telegram-process-title">Один понятный сценарий для клиента</h2></div><ol><li><span>1</span><div><h3>Выбрать услугу</h3><p>Бот покажет только активные услуги компании.</p></div></li><li><span>2</span><div><h3>Выбрать специалиста и время</h3><p>Занятые интервалы и время, которого не хватит на услугу, не предлагаются.</p></div></li><li><span>3</span><div><h3>Управлять визитом</h3><p>Подтверждение, перенос и отмена доступны в том же чате.</p></div></li></ol></section>
    <section className="marketing-section" aria-labelledby="telegram-business-title"><p className="eyebrow">Для бизнеса услуг</p><h2 id="telegram-business-title">Бот для онлайн-записи клиентов в Telegram</h2><p className="marketing-section-copy">Slotty подходит компаниям и самостоятельным специалистам, которые работают по предварительной записи. Клиенту не нужно звонить, ждать ответа или устанавливать отдельное приложение: он открывает знакомый чат и проходит запись самостоятельно.</p><div className="capability-grid"><article><CalendarCheck size={21} aria-hidden="true" /><h3>Только доступное время</h3><p>Бот сверяет расписание сотрудника, длительность услуги и уже созданные визиты. Клиент видит только те интервалы, в которые услуга действительно помещается.</p></article><article><UserRoundCheck size={21} aria-hidden="true" /><h3>Услуга и специалист</h3><p>Перед выбором времени клиент указывает нужную услугу и исполнителя. Новая запись сохраняется с выбранными параметрами и появляется в рабочей панели.</p></article><article><BellRing size={21} aria-hidden="true" /><h3>Подтверждение в чате</h3><p>После оформления клиент получает понятное подтверждение. Администратор видит визит в общем расписании без переноса данных из переписки вручную.</p></article></div></section>
    <section className="marketing-flow"><div><p className="eyebrow">Что происходит дальше</p><h2>Telegram для клиента, единая панель для команды</h2><p className="marketing-flow-copy">Клиент управляет своим визитом через бота, а владелец и сотрудники работают с теми же данными в Slotty.</p></div><ol><li><span>01</span><div><h3>Запись попадает в расписание</h3><p>В панели отображаются дата, время, услуга, сотрудник и статус визита.</p></div></li><li><span>02</span><div><h3>Свободные слоты пересчитываются</h3><p>Время, занятое услугой, перестаёт предлагаться следующим клиентам.</p></div></li><li><span>03</span><div><h3>Изменения синхронизируются</h3><p>При переносе или отмене расписание обновляется, а освободившийся интервал снова можно использовать.</p></div></li></ol></section>
    <section className="marketing-section"><p className="eyebrow">После записи</p><h2>Коммуникация продолжается автоматически</h2><div className="capability-grid capability-grid-four"><article><BellRing size={21} aria-hidden="true" /><h3>Напоминания</h3><p>Сообщения перед визитом помогают клиенту подтвердить планы или вовремя изменить запись.</p></article><article><CalendarClock size={21} aria-hidden="true" /><h3>Перенос и отмена</h3><p>Изменения проходят через контролируемый сценарий и сразу отражаются в панели.</p></article><article><ListRestart size={21} aria-hidden="true" /><h3>Лист ожидания</h3><p>Освободившийся слот предлагается клиенту, который ожидает подходящее время.</p></article><article><MessageSquareText size={21} aria-hidden="true" /><h3>Отзывы</h3><p>После завершения услуги клиент может поставить оценку через Telegram.</p></article></div></section>
    <section className="marketing-faq" aria-labelledby="telegram-faq"><p className="eyebrow">Вопросы</p><h2 id="telegram-faq">Об онлайн-записи через Telegram</h2><div><details><summary>Нужен ли отдельный бот?</summary><p>Да. Владелец создаёт бота через BotFather и подключает его токен в защищённом разделе Slotty. После подключения услуги и свободное время компании становятся доступны клиентам в этом боте.</p></details><details><summary>Нужно ли клиенту регистрироваться в Slotty?</summary><p>Нет. Клиент взаимодействует с подключённым Telegram-ботом и не создаёт отдельную учётную запись в панели компании.</p></details><details><summary>Может ли клиент занять уже забронированное время?</summary><p>Нет. Перед созданием записи Slotty повторно проверяет доступность полного интервала услуги. Если услуга длится час, занятый ею период не предлагается как свободный.</p></details><details><summary>Можно ли перенести или отменить запись в Telegram?</summary><p>Да. Клиент проходит предусмотренный сценарий в боте. При переносе выбирается новое доступное время, после чего расписание обновляется.</p></details><details><summary>Где администратор увидит новую запись?</summary><p>Новый визит появляется в панели Slotty вместе с услугой, сотрудником, временем и статусом. Там же команда работает с расписанием и изменениями.</p></details></div></section>
  </MarketingLayout>;
}
