import { ArrowRight, BellRing, CalendarClock, ListRestart, MessageSquareText, Send } from 'lucide-react';
import { Link } from 'react-router-dom';
import { trackEvent } from '../analytics';
import { MarketingLayout } from './MarketingLayout';

export function TelegramBookingPage() {
  return <MarketingLayout>
    <section className="marketing-hero"><nav className="breadcrumbs" aria-label="Хлебные крошки"><Link to="/">Главная</Link><span aria-hidden="true">/</span><span>Запись через Telegram</span></nav><p className="eyebrow">Telegram-бот для записи</p><h1>Клиент записывается сам — прямо в Telegram</h1><p>Бот показывает услуги, сотрудников и только действительно свободное время. Запись синхронизируется с рабочим расписанием Slotty.</p><div className="landing-actions"><Link className="primary-button lime-button" to="/app?mode=register" onClick={() => { trackEvent('landing_start_trial', { source: 'telegram_booking' }); trackEvent('registration_start', { source: 'telegram_booking' }); }}>Подключить Slotty <ArrowRight size={17} /></Link><Link className="text-button" to="/online-zapis">Возможности онлайн-записи</Link></div></section>
    <section className="telegram-process" aria-labelledby="telegram-process-title"><div><Send size={30} aria-hidden="true" /><p className="eyebrow">Без переписки</p><h2 id="telegram-process-title">Один понятный сценарий для клиента</h2></div><ol><li><span>1</span><div><h3>Выбрать услугу</h3><p>Бот покажет только активные услуги компании.</p></div></li><li><span>2</span><div><h3>Выбрать специалиста и время</h3><p>Занятые интервалы и время, которого не хватит на услугу, не предлагаются.</p></div></li><li><span>3</span><div><h3>Управлять визитом</h3><p>Подтверждение, перенос и отмена доступны в том же чате.</p></div></li></ol></section>
    <section className="marketing-section"><p className="eyebrow">После записи</p><h2>Коммуникация продолжается автоматически</h2><div className="capability-grid capability-grid-four"><article><BellRing size={21} aria-hidden="true" /><h3>Напоминания</h3><p>Сообщения перед визитом помогают клиенту подтвердить планы или вовремя изменить запись.</p></article><article><CalendarClock size={21} aria-hidden="true" /><h3>Перенос и отмена</h3><p>Изменения проходят через контролируемый сценарий и сразу отражаются в панели.</p></article><article><ListRestart size={21} aria-hidden="true" /><h3>Лист ожидания</h3><p>Освободившийся слот предлагается клиенту, который ожидает подходящее время.</p></article><article><MessageSquareText size={21} aria-hidden="true" /><h3>Отзывы</h3><p>После завершения услуги клиент может поставить оценку через Telegram.</p></article></div></section>
    <section className="marketing-faq" aria-labelledby="telegram-faq"><p className="eyebrow">Вопросы</p><h2 id="telegram-faq">О Telegram-интеграции</h2><div><details><summary>Нужен ли отдельный бот?</summary><p>Да. Владелец создаёт бота через BotFather и подключает его токен в защищённом разделе Slotty.</p></details><details><summary>Может ли клиент занять уже забронированное время?</summary><p>Нет. Перед созданием записи Slotty повторно проверяет доступность полного интервала услуги.</p></details><details><summary>Можно ли перенести запись в Telegram?</summary><p>Да. Клиент выбирает новое доступное время, после чего расписание обновляется.</p></details></div></section>
  </MarketingLayout>;
}
